### PR TITLE
Added support for auto-injecting dependencies

### PR DESCRIPTION
**Pull request by IOAyman**

### CODE REVIEW

**Comment by IOAyman** [comment]
Thanks!

**Comment by elisecode247** [comment]
Thank you! I kept all your changes and updated the readme so that it's more clear. I'm going to update the video soon to include the extra step.

**Comment by IOAyman** [comment]
Yeah, I've noticed that and wanted to mention a couple of things in my PR:

- I've made it so you [don't have to](https://github.com/elisecode247/Basic-Front-End-Project/pull/1/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R6) `bower install` at the first time, so that extra [5th step](https://github.com/elisecode247/Basic-Front-End-Project/blob/20190c5/README.md#getting-started) is not needed.

- A user may want to install some extra dependencies, other than bootstrap/jquery. It's not mentioned in the guide.

- [I think](https://github.com/elisecode247/Basic-Front-End-Project/pull/1/files#diff-04c6e90faac2675aa89e2176d2eec7d8R23) it is better to explicitly specify to use `bower` for managing frontend dependencies and leaving `npm` only for backend ones.
Mainly, so they can be wired into the `index.html`, and it's kind of a _convention_.

**Comment by elisecode247** [comment]
I didn't know that was what bower was for, so I'm definitely learning something new from you. I'm going to test it out and record my screen so I can update the video and readme files.

**Comment by IOAyman** [comment]
Glad to hear that 😄 Happy to share with you what I've learned, fellow camper :) 

FYI:  [npm](http://npmjs.com) [bower](http://bower.io) and [yarn](http://yarnpkg.com) are all package managers, they do pretty much the same thing, with some differences, little but important differences :) 

Maybe we can talk about that later on, if you like.

**Comment by elisecode247** [comment]
Thanks, that would be great. I am going to work on it over the next week or so and get your feedback on it. After that, I'll share it in the FCC forums.

**Pull request merged**
